### ISSUE TITLE
Share extension: Various problems saving when PDF is unavailable

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#401]
Bunch of different problems here.

If I go to https://www.sciencedirect.com/science/article/abs/pii/S0968090X21004289 and try to save, I get this:

![share-ext](https://user-images.githubusercontent.com/783082/146431925-eeca7600-3247-4eee-ba1f-18cbb0d2e0a2.jpeg)

1) It's correct that the PDF isn't available, but the item is fine, so it shouldn't say "You can still save this page as a webpage item.", which only applies when the translator itself fails.

2) The dialog is cut off. That's probably a general problem with a long title, though it might only be happening here because of the extra line at the bottom, which shouldn't actually be there.

3) If I tap Save to Zotero with the app configured for a WebDAV URL that's currently available (WebDAV server on localhost that's shut down), I get this:

![IMG_55DB5D5D2D69-1](https://user-images.githubusercontent.com/783082/146444331-27bd3c4a-992b-4b3a-87bd-041af82f2769.jpeg)

What it's actually trying to say is that the *file* can't be uploaded and is saved to my local library. The item can still be uploaded. That distinction maybe isn't that important in general, but in the case of WebDAV this is confusing, and you're likely to think there's a problem with the Zotero servers.

4) When that happens, I can only click Cancel to close the dialog. It makes sense to have to close the dialog manually, so that you have time to read the error, but you're not cancelling — if anything, there should just be a Done or OK button in place of "Save to Zotero", and Cancel should be disabled.

5) But, most importantly, this is of course wrong anyway, because there is no file available, so it shouldn't be trying to upload anything to begin with. Indeed, if I change to Zotero Storage and try again, the dialog closes, but it saves and uploads a ScienceDirect HTML page as the PDF, and when I tap on the item I get "Unable to Display Document" in the PDF viewer. So we still don't seem to be detecting that a PDF wasn't saved and discarding the file, or at least aren't doing so in the ScienceDirect case that uses a browser for the download. Debug ID D337262551. (Ignore the 412 part, which is from the other issue.)

**Comment by michalrentka** [comment]
@dstillman everything should be fixed. I changed `Error uploading item. The item was saved to your local library.` to `Error uploading attachment to your WebDAV server. The item was saved to your library.` to highlight it's a WebDAV issue.

**Comment by dstillman** [comment]
> Error uploading attachment to your WebDAV server. The item was saved to your library.

The file is still saved to your library, though, right? So could just be `Error uploading attachment to WebDAV server`.

**Comment by michalrentka** [comment]
Sure, I'll change that

**Comment by dstillman** [comment]
Still seeing these in 174:

1) Dialog still cut off (#403)
2) "Save to Zotero" button disabled if PDF isn't available

![IMG_688547D55792-1](https://user-images.githubusercontent.com/783082/147005348-4ea324bb-eedc-450e-9b6f-0240ae383e7b.jpeg)
